service: greet-bot-svc
app: greet-bot
org: gauravdas

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    APP_ID: ${param:APP_ID}
    PRIVATE_KEY: ${param:PRIVATE_KEY}
    WEBHOOK_SECRET: ${param:WEBHOOK_SECRET}
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  webhooks:
    handler: handler.webhooks
    events:
      - httpApi:
          # path: /api/github/webhooks
          path: /
          method: post
